### ISSUE TITLE
No prefixes are shown for reforged stat-less items such as accessories in Color mode

### ISSUE THREAD

**Issue by Nordblum** [Xahlicem/XItemStats#1]
For example, Menacing Shackle doesn't display +4% damage if the Color option is chosen. Same goes for any other accessories and armor if Reforge Armor mod is installed. Disabling Color option restores the prefixes. I think the Color option shouldn't affect accessories at all.

**Comment by Xahlicem** [comment]
Thank you for pointing this out.
update to 1.3.1 (71c43dfea0f0153a80c749f9e7b48ae9452b764d) has fixed this issue!
